export const sectors = [
    { id: 2, name: 'Raw Materials & Chemicals' },
    { id: 3, name: 'Machinery & Equipment' },
    { id: 4, name: 'Eletronics & Eletrical' },
    { id: 5, name: 'Automotive & Transportation' },
    { id: 6, name: 'Textile & Apparel' },
    { id: 7, name: 'Food & Beverage' },
    { id: 9, name: 'Construction & Real Estate' },
    { id: 10, name: 'Services (consulting, logistics, etc)' },
    { id: 11, name: 'Industrial Supplies' },
    { id: 12, name: 'Packaging & Printing' },
    { id: 13, name: 'Health & Beauty' },
    { id: 14, name: 'Home & Garden' },
    { id: 15, name: 'Sport & Entertainment' },
    { id: 16, name: 'Office & School Supplies' },
    { id: 17, name: 'Agriculture & Livestock' },
    { id: 18, name: 'Personal Protective Equipment (PPE)' },
    { id: 19, name: 'Other' },
];
