export const sectors = [
    { id: 2, name: 'Arts & Entertainment' },
    { id: 3, name: 'Autos & Vehicles' },
    { id: 4, name: 'Beauty & Fitness' },
    { id: 5, name: 'Books & Literature' },
    { id: 6, name: 'Business & Industrials' },
    { id: 7, name: 'Computers & Eletronics' },
    { id: 8, name: 'Finance' },
    { id: 9, name: 'Food & Drink' },
    { id: 10, name: 'Games' },
    { id: 11, name: 'Health' },
    { id: 12, name: 'Hobbies & Leisure' },
    { id: 13, name: 'Home & Garden' },
    { id: 14, name: 'Internet & Telecom' },
    { id: 15, name: 'Jobs & Education' },
    { id: 16, name: 'Law & Government' },
    { id: 17, name: 'News' },
    { id: 18, name: 'Online Communities' },
    { id: 19, name: 'People & Society' },
    { id: 20, name: 'Pets & Animals' },
    { id: 21, name: 'Real Estate' },
    { id: 22, name: 'Reference' },
    { id: 23, name: 'Science' },
    { id: 24, name: 'Shopping' },
    { id: 25, name: 'Sports' },
    { id: 26, name: 'Travel' },
    { id: 27, name: 'Other' },
];
