export const nav = [
    {
		name: 'Home',
		id: 'home-link',
		url: '/',
		isPrivate: false,
		className: 'header__item',
		key: 0,
	},
	{
		name: 'Features',
		id: 'features-link',
		url: '/features',
		isPrivate: false,
		className: 'header__item',
		key: 3,
	},
	{
		name: 'About',
		id: 'about-link',
		url: '/about',
		isPrivate: false,
		className: 'header__item',
		key: 1,
	},
	{
		name: 'Contact',
		id: 'contact-link',
		url: '/contact',
		isPrivate: false,
		className: 'header__item',
		key: 2,
	},
	{
		name: 'FAQ',
		id: 'faq-link',
		url: '/faq',
		isPrivate: false,
		className: 'header__item',
		key: 4,
	},
];