name: 'Publish on Netlify: Development'

on:
  push:
    branches:
      - development

jobs:
  Deploy:
      runs-on: ubuntu-latest

      steps:
        # Checkout the code in the repo
        - name: Checkout Code
          uses: actions/checkout@v3

        # Install NodeJS
        - name: Use Node v16
          uses: actions/setup-node@v3
          with: 
            node-version: '16'

        # Install yarn and build the project
        - run: npm install --location=global yarn
        - run: yarn install
        ## - run: yarn build

        # Run Cypress E2E tests
        - name: Run Cypress E2E tests
          uses: cypress-io/github-action@v4.2.0
          with:
            build: yarn build
            start: yarn start
            browser: chrome

        # Deploy to production
        - name: Deploy to Netlify
        - uses: jsmrcaga/action-netlify-deploy@master
          with: 
            args: deploy --dir=build --alias="blendot" --open
            github-token: ${{ secrets.GITHUB_TOKEN }}
            deploy-message: "Deploy from GitHub Actions"
            enable-pull-request-comment: false
            production-branch: development
          env: 
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
