name: 'Development'

on:
  push:
    branches:
      - development

jobs:
  Deploy:
      runs-on: ubuntu-latest

      steps:
        # Get the code from the repo
        - name: Checkout Code
          uses: actions/checkout@v3

        # Install NodeJS
        - name: Use Node v16
          uses: actions/setup-node@v3
          with: 
            node-version: '16'

        # Run yarn
        - run: npm install --location=global yarn
        - run: yarn install
        - run echo "FOO:false" >> $CI
        - run: echo $CI
        - run: yarn run build

        # Deploy to Netlify
        - name: Deploy to Netlify
          uses: netlify/actions/cli@master
          env: 
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          with: 
            args: deploy --dir=build --prod
            secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
            NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
            NETLIFY_DEPLOY_TO_PROD: true
