name: "Build and Deploy"

on: 
  push:
    branch:
      - add-features

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: "Run a one-line script"
        run: npm test