name: 'Netlify Deploy'

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - development

jobs:
  Deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

    # Install NodeJS
      - name: Use Node v16.10
        uses: actions/setup-node@v3
        with: 
          node-version: '16.10.0'

      # Run yarn
      - name: Install project dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command

    # Run yarn
      - name: Build the project
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command

      - name: Deploy to Production
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
