name: Cypress Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  cypress-run:
      runs-on: ubuntu-latest

      permissions: write-all
      
      steps:
        # Get the code from the repo
        - name: Checkout Code
          uses: actions/checkout@v2

        # Install NodeJS
        - name: Use Node v16
          uses: actions/setup-node@v3
          with: 
            node-version: '16'

        # Run yarn
        - name: Install Yarn
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: install # will run `yarn install` command

        - name: Run Build
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: build # will run `yarn build` command

        - name: Cypress open
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: test

        # Build the app with Cypress
        - name: Run E2E on Cypress
          uses: cypress-io/github-action@v4
          with: 
          build: 
            start: yarn start
