name: Cypress Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

  permissions: read-all|write-all

jobs:
  cypress-run:
      runs-on: ubuntu-latest

      steps:
        # Get the code from the repo
        - name: Checkout Code
          uses: actions/checkout@v2

        # Install NodeJS
        - name: Use Node v14
          uses: actions/setup-node@v3
          with: 
            node-version: '14'

        # Run yarn
        - name: Install Yarn
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: install # will run `yarn install` command

        - name: Run Build
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: build # will run `yarn build` command

        # Build the app with Cypress
        - name: Run Cypress
          uses: cypress-io/github-action@v4
          with: 
            start: yarn start
